#!/usr/bin/env python


import sys

import vanilla


def main():
    h = vanilla.Hub()
    conn = h.tcp.connect(host='127.0.0.1', port=9000)
    for i in xrange(100):
        conn.send('foo.png\n')
        conn.recv_partition('\n')


if __name__ == '__main__':
    import logging
    logging.basicConfig()
    sys.exit(main())
