#!/usr/bin/env python


import collections
import shlex
import sys

import cjson

import vanilla


EXIF_COMMAND = \
    '/usr/bin/env exiftool -stay_open True -@ - -common_args  -j -b -g'


class Exifd(object):
    def __init__(self, h):
        self.h = h

        self.child = self.h.process.execv(shlex.split(EXIF_COMMAND))

        # TODO: ganky
        sender, recver = self.h.router()
        self.child.stdout.pipe(sender)
        self.child.stderr.pipe(sender)
        import vanilla.message
        self.stream = vanilla.message.Stream(recver)

    def query(self, name):
        self.child.stdin.send('%s\n-execute\n' % name)
        response = self.stream.recv_partition('\n{ready}\n')
        try:
            response = cjson.decode(response)
            # strip wrapper
            response = response[0]
            response = cjson.encode(response)
        except cjson.DecodeError:
            response = cjson.encode({'error': response.strip()})
        return response


def main():
    h = vanilla.Hub()

    workers = h.queue(10).pipe(h.dealer())
    for i in xrange(10):
        workers.send(Exifd(h))

    server = h.tcp.listen(port=9000)
    print 'Listening on 127.0.0.1:%s' % server.port

    class Stats(object):
        def __init__(self):
            self.requests = 0

            @h.spawn
            def _():
                for _ in h.pulse(1000):
                    print 'requests_per_second:%s' % self.requests
                    self.requests = 0

    stats = Stats()

    def serve(conn):
        try:
            while True:
                name = conn.recv_partition('\n')
                worker = workers.recv()
                response = worker.query(name)
                workers.send(worker)
                conn.send(response)
                conn.send('\n')
                stats.requests += 1
        except vanilla.Halt:
            conn.close()
            return

    @h.spawn
    def _():
        while True:
            conn = server.recv()
            h.spawn(serve, conn)


    h.stop_on_term()


if __name__ == '__main__':
    import logging
    logging.basicConfig()
    sys.exit(main())
